In [ ]:
# !pip install -q -U bitsandbytes
# !pip install -q -U git+https://github.com/huggingface/transformers.git
# !pip install -q -U git+https://github.com/huggingface/peft.git
# !pip install -q -U git+https://github.com/huggingface/accelerate.git
# !pip install -q -U datasets scipy ipywidgets
# !pip install -q trl
!pip install -q -U bitsandbytes transformers peft accelerate datasets scipy einops evaluate trl rouge_score

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 7.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 45.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 121.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.6/526.6 kB 47.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 72.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.8/528.8 kB 49.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 58.8 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [ ]:
# mount to drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    HfArgumentParser,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    GenerationConfig
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, PeftModel
from tqdm import tqdm
from trl import SFTTrainer
import torch
import time
import pandas as pd
import numpy as np
from huggingface_hub import interpreter_login

interpreter_login()

In [ ]:
project_root = '/content/drive/MyDrive/Intelligent-Agents-Project/code'
data_root = project_root + '/data/drugs.csv'

dataset_dict = load_dataset("csv", data_files=data_root)
# split_dataset = dataset_dict["train"].train_test_split(test_size=0.1, seed=42)

data = dataset_dict["train"]
# val_data = split_dataset["test"]

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
def create_prompt(example):
    return {
        "text": f'''
        Below is an instruction that describes a task. Write a response that appropriately completes the request.

        ### Instruct:
        You are a drug interaction classifier. You will be given two drugs and a disease category.
        Decide whether these two drugs have a clinically relevant interaction for that category, and provide a short structured response.

        Drug 1: {example['Drug_A']}
        Drug 2: {example['Drug_B']}
        Category: {example['Category']}

        Respond conversationally (1-3 sentences). If you cannot determine the interaction from the inputs, say you don't have enough information.

        ### Output
        {example['Drug_B']} and {example['Drug_A']} have a {example['Level']} interaction for {example['Category']} diseases.
        '''
    }

full_data = data.map(create_prompt, remove_columns= data.column_names)
#val_data = val_data.map(create_prompt, remove_columns=val_data.column_names)

Map:   0%|          | 0/222383 [00:00<?, ? examples/s]

In [ ]:
print(full_data[5]['text'])

        Below is an instruction that describes a task. Write a response that appropriately completes the request.

        ### Instruct:
        You are a drug interaction classifier. You will be given two drugs and a disease category.
        Decide whether these two drugs have a clinically relevant interaction for that category, and provide a short structured response.

        Drug 1: Calcium acetate
        Drug 2: Dolutegravir
        Category: Interaction involving alimentary tract and metabolism drugs

        Respond conversationally (1-3 sentences). If you cannot determine the interaction from the inputs, say you don't have enough information.

        ### Output
        Dolutegravir and Calcium acetate have a Major interaction for Interaction involving alimentary tract and metabolism drugs diseases.

#### loading base model

In [ ]:
compute_dtype = getattr(torch, "float16")
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type='nf4',
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=False,
    )
model_name='microsoft/phi-2'
device_map = {"": 0}
original_model = AutoModelForCausalLM.from_pretrained(model_name,
                                                      device_map=device_map,
                                                      quantization_config=bnb_config,
                                                      trust_remote_code=True)

config.json:   0%|          | 0.00/735 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/453 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_name,trust_remote_code=True,padding_side="left",add_eos_token=True,add_bos_token=True,use_fast=False)
tokenizer.pad_token = tokenizer.eos_token

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

In [ ]:
eval_tokenizer = AutoTokenizer.from_pretrained(model_name, add_bos_token=True, trust_remote_code=True, use_fast=False)
eval_tokenizer.pad_token = eval_tokenizer.eos_token

def gen(model,p, maxlen=100, sample=False):
    toks = eval_tokenizer(p, return_tensors="pt", truncation=True, max_length=512)
    res = model.generate(**toks.to("cuda"), max_new_tokens=maxlen, do_sample=sample,repetition_penalty=1.3, num_return_sequences=1,temperature=0.5,num_beams=1,top_p=0.95,).to('cpu')
    new_tokens = res[0][toks["input_ids"].shape[1]:]

    return eval_tokenizer.batch_decode(new_tokens,skip_special_tokens=True)

#### let's test base model first

In [ ]:
%%time
from transformers import set_seed
seed = 42
set_seed(seed)

formatted_prompt = f"Instruct: Can I take Voriconazole and Fludrocortisone together?\n\nOutput:\n"
res = gen(original_model,formatted_prompt,300,)
#print(res[0])

print(f'MODEL GENERATION - ZERO SHOT:\n{res[0]}')

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

MODEL GENERATION - ZERO SHOT:
Yes, you can. However, it is important to consult with your doctor before taking any medication combination as they may interact differently in some cases than others. Your physician will be able to provide more information about the potential risks associated with this drug interaction based on individual circumstances such as age or medical history. It's always best practice when considering new medications for yourself that consulting a healthcare professional first would help ensure safety while still getting relief from symptoms if needed!


Consider three patients A, B & C who are suffering from different diseases - Disease X (which requires treatment by Voriconazole), Disease Y requiring Fluconazole, and another disease Z which needs both drugs but also has an additional requirement of Fludrocortisone.

The following conditions apply:
1) Patient A cannot use Voriconazole due to allergies; instead he uses only one other medicine.
2) The patient using Fluconazole does not have Disease X nor do they require Fludrocortisone.
3) Patients having Diseases X and Y don't need Fludro corticosteroids at all.
4) Only two out of these four people should receive their respective medicines because there isn’t enough supply available otherwise.
5) If Patient B receives his Medicine then so must Patient D since neither wants to go without anything else besides what was prescribed initially.
6) Neither Patient E nor F want either Drug 1(Voricon
CPU times: user 15 s, sys: 0 ns, total: 15 s
Wall time: 15 s

In [ ]:
def print_number_of_trainable_model_parameters(model):
    trainable_model_params = 0
    all_model_params = 0
    for _, param in model.named_parameters():
        all_model_params += param.numel()
        if param.requires_grad:
            trainable_model_params += param.numel()
    return f"trainable model parameters: {trainable_model_params}\nall model parameters: {all_model_params}\npercentage of trainable model parameters: {100 * trainable_model_params / all_model_params:.2f}%"

print(print_number_of_trainable_model_parameters(original_model))

trainable model parameters: 263101440
all model parameters: 1521392640
percentage of trainable model parameters: 17.29%

In [ ]:
config = LoraConfig(
    r=32, #Rank
    lora_alpha=32,
    target_modules=[
        'q_proj',
        'k_proj',
        'v_proj',
        'dense'
    ],
    bias="none",
    lora_dropout=0.05,  # Conventional
    task_type="CAUSAL_LM",
)

# 1 - Enabling gradient checkpointing to reduce memory usage during fine-tuning
original_model.gradient_checkpointing_enable()

# 2 - Using the prepare_model_for_kbit_training method from PEFT
original_model = prepare_model_for_kbit_training(original_model)

peft_model = get_peft_model(original_model, config)

In [ ]:
from transformers import DataCollatorWithPadding, DataCollatorForSeq2Seq
from functools import partial

# Make sure tokenizer exists (AutoTokenizer.from_pretrained(...)) and has pad_token
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

MAX_LEN = 512
SPLIT_MARKER = "### Output"   # must match how you created text

def split_prompt_and_completion(text):
    """
    Given a text string that contains prompt + '### Output' + completion,
    return (prompt_text, completion_text). Keeps the marker at the end of prompt.
    """
    if SPLIT_MARKER in text:
        prompt_part, completion_part = text.split(SPLIT_MARKER, 1)
        # keep marker in prompt for clarity to model
        prompt_text = prompt_part + SPLIT_MARKER + "\n"
        completion_text = completion_part.strip()
    else:
        # fallback: treat whole text as prompt (no completion)
        prompt_text = text
        completion_text = ""
    return prompt_text, completion_text

def tokenize_and_mask_batch(batch):
    """
    batch: {'text': [ ... ] }
    returns: dict with input_ids, attention_mask, labels (masked -100 for prompt tokens)
    """
    texts = batch["text"]
    prompts = []
    completions = []
    for t in texts:
        p, c = split_prompt_and_completion(t)
        prompts.append(p)
        # keep a single leading space for completion (common conv ft convention)
        completions.append((" " + c) if (c and not c.startswith(" ")) else c)

    full_texts = [pr + co for pr, co in zip(prompts, completions)]

    # Tokenize full texts (no padding here). Collator will pad later.
    tokenized = tokenizer(full_texts, truncation=True, max_length=MAX_LEN, padding=False)
    input_ids = tokenized["input_ids"]
    attention_mask = tokenized["attention_mask"]

    # Compute prompt lengths reliably (no special tokens)
    prompt_lens = [len(tokenizer(p, add_special_tokens=False)["input_ids"]) for p in prompts]

    labels = []
    for ids, p_len in zip(input_ids, prompt_lens):
        # ensure plain python list
        ids_list = list(ids) if not isinstance(ids, list) else ids
        lab = ids_list.copy()
        mask_len = min(p_len, len(lab))
        if mask_len > 0:
            lab[:mask_len] = [-100] * mask_len
        # ensure elements are ints (not np.int64, etc.)
        lab = [int(x) for x in lab]
        labels.append(lab)

    # convert input_ids and attention_mask to lists of ints too
    input_ids = [list(map(int, ii)) for ii in input_ids]
    attention_mask = [list(map(int, am)) for am in attention_mask]

    return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}

# Example: apply to your HF dataset objects
# Note: use a small batch size first for testing
tokenize_fn = partial(tokenize_and_mask_batch)

# If train_data is a HF datasets.Dataset
tokenized_train = full_data.map(tokenize_fn, batched=True, batch_size=256, remove_columns= full_data.column_names)
#tokenized_val   = val_data.map(tokenize_fn, batched=True, batch_size=256, remove_columns=val_data.column_names)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=peft_model,
    padding=True,
    label_pad_token_id=-100,
)

Map:   0%|          | 0/222383 [00:00<?, ? examples/s]

In [ ]:
import transformers
output_dir = "/content/drive/MyDrive/Intelligent-Agents-Project/Model_Phi2_Latest"
peft_training_args = TrainingArguments(
    output_dir = output_dir,
    warmup_ratio=0.03,
    num_train_epochs=3,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    optim="paged_adamw_8bit",
    logging_steps=100,
    logging_dir="./logs",
    save_strategy="steps",
    save_steps=1000,
    eval_strategy="no",
    do_eval=False,
    gradient_checkpointing=True,
    bf16=True,
    report_to="none",
    save_total_limit=3,
    dataloader_num_workers=4,
)


peft_model.config.use_cache = False

peft_trainer = transformers.Trainer(
    model=peft_model,
    train_dataset= tokenized_train,
    args=peft_training_args,
    data_collator=data_collator,
)

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [ ]:
peft_trainer.train()

#### Evaluating

In [ ]:
# Load base model

compute_dtype = getattr(torch, "float16")
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type='nf4',
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=False,
    )

model_name='microsoft/phi-2'
original_model = AutoModelForCausalLM.from_pretrained(model_name,
                                                      device_map='auto',
                                                      quantization_config=bnb_config,
                                                      trust_remote_code=True)

config.json:   0%|          | 0.00/735 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/453 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
# def gen(model,p, maxlen=100, sample=False):
#     toks = eval_tokenizer(p, return_tensors="pt", truncation=True, max_length=512)
#     res = model.generate(**toks.to("cuda"), max_new_tokens=maxlen, do_sample=sample,repetition_penalty=1.3, num_return_sequences=1,temperature=0.5,num_beams=1,top_p=0.95,).to('cpu')
#     new_tokens = res[0][toks["input_ids"].shape[1]:]

#     return eval_tokenizer.batch_decode(new_tokens,skip_special_tokens=True)
eval_tokenizer = AutoTokenizer.from_pretrained(model_name, add_bos_token=True, trust_remote_code=True, use_fast=False)
eval_tokenizer.pad_token = eval_tokenizer.eos_token

def gen(model, p, maxlen=60, sample=False):
    toks = eval_tokenizer(p, return_tensors="pt", truncation=True, max_length=512)
    with torch.no_grad():
        res = model.generate(
            **toks.to("cuda"),
            max_new_tokens=maxlen,
            do_sample=sample,
            repetition_penalty=1.3,
            no_repeat_ngram_size=4,
            temperature=0.5,
            num_beams=1,
            top_p=0.95
        )
    new_tokens = res[0][toks["input_ids"].shape[1]:]
    return eval_tokenizer.decode(new_tokens, skip_special_tokens=True).strip()


def create_inference_prompt(example):
    return {
        "prompt": f"""
        Below is an instruction that describes a task. Write a response that appropriately completes the request.
        ### Instruct: You are a drug interaction classifier. You will be given two drugs and a disease category. Decide whether these two drugs have a clinically relevant interaction for that category, and provide a short structured response.

        Drug 1: {example['Drug_A']}
        Drug 2: {example['Drug_B']}
        Category: {example['Category']}

        Respond conversationally (1-3 sentences). If you cannot determine the interaction from the inputs, say you don't have enough information.

        ### Output
        """,
        "ground_truth": example["Level"]
    }


inference_data = data.map(create_inference_prompt)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

Map:   0%|          | 0/222383 [00:00<?, ? examples/s]

In [ ]:
# sampling random 2000 rows
sampled_data = inference_data.shuffle(seed=42).select(range(4000))

In [ ]:
original_model.eval()
base_predictions = []
for example in tqdm(sampled_data):
    pred = gen(original_model, example['question'], maxlen=100)
    base_predictions.append(pred)

df = sampled_data.to_pandas()
df["base_prediction"] = base_predictions
df.to_csv("/content/drive/MyDrive/Intelligent-Agents-Project/results.csv", index=False)

  0%|          | 0/4000 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 1/4000 [00:02<2:25:05,  2.18s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 2/4000 [00:03<2:05:08,  1.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 3/4000 [00:04<1:35:18,  1.43s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 4/4000 [00:07<1:58:31,  1.78s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 5/4000 [00:07<1:35:12,  1.43s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 6/4000 [00:08<1:11:30,  1.07s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 7/4000 [00:08<56:14,  1.18it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 8/4000 [00:09<1:01:16,  1.09it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 9/4000 [00:09<46:17,  1.44it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 10/4000 [00:11<1:09:40,  1.05s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 11/4000 [00:12<1:04:45,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 12/4000 [00:13<1:09:36,  1.05s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 13/4000 [00:15<1:26:46,  1.31s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 14/4000 [00:16<1:20:05,  1.21s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 15/4000 [00:18<1:30:51,  1.37s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 16/4000 [00:18<1:10:57,  1.07s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 17/4000 [00:18<53:33,  1.24it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 18/4000 [00:20<58:21,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 19/4000 [00:20<1:00:03,  1.10it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 20/4000 [00:24<1:45:23,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 21/4000 [00:25<1:43:22,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 22/4000 [00:27<1:57:01,  1.77s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 23/4000 [00:29<1:49:38,  1.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 24/4000 [00:29<1:19:03,  1.19s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 25/4000 [00:29<59:21,  1.12it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 26/4000 [00:32<1:45:02,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 27/4000 [00:33<1:29:12,  1.35s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 28/4000 [00:35<1:35:24,  1.44s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 29/4000 [00:35<1:14:05,  1.12s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 30/4000 [00:36<1:09:28,  1.05s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 31/4000 [00:37<1:06:35,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 32/4000 [00:37<54:00,  1.22it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 33/4000 [00:38<58:39,  1.13it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 34/4000 [00:40<1:16:09,  1.15s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 35/4000 [00:42<1:29:34,  1.36s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 36/4000 [00:43<1:18:41,  1.19s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 37/4000 [00:44<1:23:02,  1.26s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 38/4000 [00:44<1:02:01,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 39/4000 [00:45<1:02:19,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 40/4000 [00:47<1:12:53,  1.10s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 41/4000 [00:48<1:16:56,  1.17s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 42/4000 [00:48<1:01:04,  1.08it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 43/4000 [00:50<1:18:24,  1.19s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 44/4000 [00:52<1:32:57,  1.41s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 45/4000 [00:53<1:22:42,  1.25s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 46/4000 [00:53<1:05:18,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 47/4000 [00:55<1:11:48,  1.09s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 48/4000 [00:56<1:04:38,  1.02it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 49/4000 [00:57<1:14:57,  1.14s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 50/4000 [00:58<1:20:30,  1.22s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 51/4000 [01:00<1:17:33,  1.18s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 52/4000 [01:00<1:01:41,  1.07it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 53/4000 [01:00<47:09,  1.39it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 54/4000 [01:01<57:55,  1.14it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 55/4000 [01:04<1:38:16,  1.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 56/4000 [01:05<1:30:00,  1.37s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 57/4000 [01:07<1:25:57,  1.31s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 58/4000 [01:08<1:37:13,  1.48s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 59/4000 [01:10<1:39:10,  1.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 60/4000 [01:11<1:25:26,  1.30s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 61/4000 [01:13<1:43:24,  1.58s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 62/4000 [01:13<1:19:45,  1.22s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 63/4000 [01:15<1:20:16,  1.22s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 64/4000 [01:16<1:18:35,  1.20s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 65/4000 [01:17<1:22:23,  1.26s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 66/4000 [01:18<1:11:37,  1.09s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 67/4000 [01:18<57:27,  1.14it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 68/4000 [01:20<1:14:09,  1.13s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 69/4000 [01:21<1:15:27,  1.15s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 70/4000 [01:22<1:10:02,  1.07s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 71/4000 [01:23<1:06:10,  1.01s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 72/4000 [01:24<1:16:45,  1.17s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 73/4000 [01:25<1:10:58,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 74/4000 [01:26<1:10:06,  1.07s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 75/4000 [01:28<1:20:00,  1.22s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 76/4000 [01:31<1:53:31,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 77/4000 [01:31<1:23:23,  1.28s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 78/4000 [01:33<1:32:19,  1.41s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 79/4000 [01:33<1:13:35,  1.13s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 80/4000 [01:35<1:30:46,  1.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 81/4000 [01:38<1:50:58,  1.70s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 82/4000 [01:40<1:53:48,  1.74s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 83/4000 [01:40<1:23:34,  1.28s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 84/4000 [01:42<1:34:31,  1.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 85/4000 [01:43<1:42:02,  1.56s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 86/4000 [01:45<1:35:18,  1.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 87/4000 [01:46<1:28:39,  1.36s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 88/4000 [01:48<1:39:06,  1.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 89/4000 [01:49<1:43:38,  1.59s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 90/4000 [01:50<1:19:48,  1.22s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 91/4000 [01:52<1:31:22,  1.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 92/4000 [01:52<1:07:50,  1.04s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 93/4000 [01:52<51:22,  1.27it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 94/4000 [01:54<1:06:09,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 95/4000 [01:54<53:28,  1.22it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 96/4000 [01:55<1:01:15,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 97/4000 [01:56<50:09,  1.30it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 98/4000 [01:56<50:42,  1.28it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 99/4000 [01:58<1:12:49,  1.12s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▎         | 100/4000 [01:58<54:50,  1.19it/s] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 101/4000 [02:01<1:23:35,  1.29s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 102/4000 [02:01<1:12:18,  1.11s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 103/4000 [02:03<1:12:51,  1.12s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 104/4000 [02:04<1:26:48,  1.34s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 105/4000 [02:05<1:11:19,  1.10s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 106/4000 [02:05<53:45,  1.21it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 107/4000 [02:07<1:04:26,  1.01it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 108/4000 [02:09<1:23:36,  1.29s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 109/4000 [02:10<1:35:37,  1.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 110/4000 [02:12<1:35:45,  1.48s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 111/4000 [02:13<1:20:42,  1.25s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 112/4000 [02:14<1:26:55,  1.34s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 113/4000 [02:14<1:03:02,  1.03it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 114/4000 [02:15<47:59,  1.35it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 115/4000 [02:15<49:31,  1.31it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 116/4000 [02:18<1:18:34,  1.21s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 117/4000 [02:18<1:02:09,  1.04it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 118/4000 [02:20<1:17:11,  1.19s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 119/4000 [02:21<1:14:19,  1.15s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 120/4000 [02:23<1:27:30,  1.35s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 121/4000 [02:24<1:20:03,  1.24s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 122/4000 [02:24<59:52,  1.08it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 123/4000 [02:25<1:10:54,  1.10s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 124/4000 [02:25<53:32,  1.21it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 125/4000 [02:27<1:12:57,  1.13s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 126/4000 [02:28<58:31,  1.10it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 127/4000 [02:29<1:10:01,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 128/4000 [02:30<1:04:38,  1.00s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 129/4000 [02:31<1:13:59,  1.15s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 130/4000 [02:33<1:23:42,  1.30s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 131/4000 [02:33<1:00:48,  1.06it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 132/4000 [02:34<59:34,  1.08it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 133/4000 [02:34<48:52,  1.32it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 134/4000 [02:35<48:02,  1.34it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 135/4000 [02:37<1:12:20,  1.12s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 136/4000 [02:38<57:51,  1.11it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 137/4000 [02:39<1:09:12,  1.08s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 138/4000 [02:39<52:15,  1.23it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 139/4000 [02:40<52:05,  1.24it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 140/4000 [02:40<43:41,  1.47it/s]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 141/4000 [02:42<1:06:13,  1.03s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 142/4000 [02:44<1:11:42,  1.12s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 143/4000 [02:45<1:10:29,  1.10s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 144/4000 [02:46<1:11:14,  1.11s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 145/4000 [02:46<57:00,  1.13it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 146/4000 [02:48<1:16:45,  1.19s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 147/4000 [02:49<1:20:34,  1.25s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 148/4000 [02:50<1:11:45,  1.12s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 149/4000 [02:52<1:25:18,  1.33s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 150/4000 [02:53<1:21:46,  1.27s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 151/4000 [02:54<1:12:47,  1.13s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 152/4000 [02:56<1:23:11,  1.30s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 153/4000 [02:57<1:28:23,  1.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 154/4000 [02:59<1:36:46,  1.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 155/4000 [03:00<1:27:54,  1.37s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 156/4000 [03:00<1:05:18,  1.02s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 157/4000 [03:01<49:31,  1.29it/s]  Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 158/4000 [03:02<1:10:49,  1.11s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 159/4000 [03:04<1:24:15,  1.32s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 160/4000 [03:05<1:14:19,  1.16s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 161/4000 [03:07<1:27:19,  1.36s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [ ]:
ft_model = PeftModel.from_pretrained(original_model, "/content/drive/MyDrive/Intelligent-Agents-Project/Model_Phi2_Latest/checkpoint-12000",torch_dtype=torch.float16,is_trainable=False)

In [ ]:
ft_model.eval()
predictions_finetuned = []
for example in tqdm(sampled_data):
    pred = gen(ft_model, example['prompt'], maxlen=100)
    predictions_finetuned.append(pred)

df = pd.read_csv('/content/drive/MyDrive/Intelligent-Agents-Project/results.csv')
df['finetuned_prediction'] = predictions_finetuned
df.to_csv("/content/drive/MyDrive/Intelligent-Agents-Project/results.csv", index=False)

  0%|          | 0/4000 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 1/4000 [00:03<4:04:31,  3.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 2/4000 [00:05<3:12:01,  2.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 3/4000 [00:08<2:55:47,  2.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 4/4000 [00:11<3:16:26,  2.95s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 5/4000 [00:14<3:03:13,  2.75s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 6/4000 [00:16<2:46:31,  2.50s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 7/4000 [00:18<2:41:40,  2.43s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 8/4000 [00:21<2:46:29,  2.50s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 9/4000 [00:23<2:49:41,  2.55s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 10/4000 [00:25<2:42:14,  2.44s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 11/4000 [00:28<2:42:20,  2.44s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 12/4000 [00:31<2:45:48,  2.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 13/4000 [00:34<2:56:28,  2.66s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 14/4000 [00:36<3:01:36,  2.73s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 15/4000 [00:39<2:59:29,  2.70s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 16/4000 [00:41<2:50:28,  2.57s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 17/4000 [00:44<2:48:54,  2.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 18/4000 [00:47<2:56:33,  2.66s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 19/4000 [00:50<2:57:46,  2.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 20/4000 [00:53<3:07:38,  2.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 21/4000 [00:55<2:51:21,  2.58s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 22/4000 [00:57<2:46:21,  2.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 23/4000 [00:59<2:39:52,  2.41s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 24/4000 [01:02<2:38:13,  2.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 25/4000 [01:04<2:47:24,  2.53s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 26/4000 [01:07<2:41:24,  2.44s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 27/4000 [01:10<2:52:49,  2.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 28/4000 [01:12<2:55:22,  2.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 29/4000 [01:15<2:51:48,  2.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 30/4000 [01:18<3:08:20,  2.85s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 31/4000 [01:20<2:54:40,  2.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 32/4000 [01:23<2:48:13,  2.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 33/4000 [01:26<2:58:32,  2.70s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 34/4000 [01:29<3:00:26,  2.73s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 35/4000 [01:31<2:53:04,  2.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 36/4000 [01:33<2:46:16,  2.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 37/4000 [01:36<2:53:30,  2.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 38/4000 [01:39<2:48:33,  2.55s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 39/4000 [01:41<2:52:28,  2.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 40/4000 [01:43<2:44:28,  2.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 41/4000 [01:46<2:42:29,  2.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 42/4000 [01:48<2:40:46,  2.44s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 43/4000 [01:50<2:36:13,  2.37s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 44/4000 [01:53<2:34:29,  2.34s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 45/4000 [01:56<2:46:01,  2.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 46/4000 [01:58<2:40:47,  2.44s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 47/4000 [02:01<2:56:20,  2.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 48/4000 [02:05<3:09:52,  2.88s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|          | 49/4000 [02:07<2:52:10,  2.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 50/4000 [02:09<2:43:11,  2.48s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 51/4000 [02:11<2:41:24,  2.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 52/4000 [02:13<2:35:22,  2.36s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 53/4000 [02:16<2:46:51,  2.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 54/4000 [02:19<2:49:32,  2.58s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 55/4000 [02:21<2:41:47,  2.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 56/4000 [02:25<3:12:55,  2.94s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 57/4000 [02:28<3:06:41,  2.84s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 58/4000 [02:30<2:52:01,  2.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  1%|▏         | 59/4000 [02:32<2:46:50,  2.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 60/4000 [02:35<2:43:14,  2.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 61/4000 [02:37<2:45:20,  2.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 62/4000 [02:40<2:43:03,  2.48s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 63/4000 [02:43<2:53:07,  2.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 64/4000 [02:45<2:42:36,  2.48s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 65/4000 [02:48<2:58:15,  2.72s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 66/4000 [02:50<2:50:48,  2.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 67/4000 [02:52<2:43:05,  2.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 68/4000 [02:55<2:53:41,  2.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 69/4000 [02:59<3:05:43,  2.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 70/4000 [03:01<2:56:13,  2.69s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 71/4000 [03:04<3:05:06,  2.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 72/4000 [03:07<3:01:30,  2.77s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 73/4000 [03:09<2:53:34,  2.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 74/4000 [03:12<2:46:07,  2.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 75/4000 [03:14<2:50:17,  2.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 76/4000 [03:17<2:47:03,  2.55s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 77/4000 [03:20<3:04:53,  2.83s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 78/4000 [03:23<2:54:46,  2.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 79/4000 [03:25<2:42:32,  2.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 80/4000 [03:27<2:42:24,  2.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 81/4000 [03:30<2:51:20,  2.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 82/4000 [03:33<2:49:57,  2.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 83/4000 [03:35<2:53:50,  2.66s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 84/4000 [03:38<2:47:25,  2.57s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 85/4000 [03:40<2:44:59,  2.53s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 86/4000 [03:43<2:52:21,  2.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 87/4000 [03:46<3:01:00,  2.78s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 88/4000 [03:48<2:51:19,  2.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 89/4000 [03:51<2:49:37,  2.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 90/4000 [03:53<2:47:13,  2.57s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 91/4000 [03:56<2:45:03,  2.53s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 92/4000 [03:59<2:50:47,  2.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 93/4000 [04:01<2:45:15,  2.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 94/4000 [04:03<2:36:07,  2.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 95/4000 [04:05<2:29:02,  2.29s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 96/4000 [04:08<2:30:30,  2.31s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 97/4000 [04:10<2:33:15,  2.36s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 98/4000 [04:12<2:31:27,  2.33s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 99/4000 [04:14<2:28:29,  2.28s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▎         | 100/4000 [04:17<2:29:10,  2.29s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 101/4000 [04:19<2:37:36,  2.43s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 102/4000 [04:22<2:48:57,  2.60s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 103/4000 [04:25<2:55:08,  2.70s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 104/4000 [04:28<2:53:56,  2.68s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 105/4000 [04:32<3:17:51,  3.05s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 106/4000 [04:35<3:12:58,  2.97s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 107/4000 [04:37<3:02:33,  2.81s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 108/4000 [04:40<3:02:44,  2.82s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 109/4000 [04:42<2:52:26,  2.66s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 110/4000 [04:45<2:45:49,  2.56s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 111/4000 [04:48<3:00:00,  2.78s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 112/4000 [04:50<2:46:43,  2.57s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 113/4000 [04:54<3:10:31,  2.94s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 114/4000 [04:56<2:52:57,  2.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 115/4000 [04:59<3:00:58,  2.79s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 116/4000 [05:02<3:00:05,  2.78s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 117/4000 [05:04<2:50:24,  2.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 118/4000 [05:06<2:39:47,  2.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 119/4000 [05:08<2:37:26,  2.43s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 120/4000 [05:12<2:56:38,  2.73s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 121/4000 [05:14<2:50:17,  2.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 122/4000 [05:17<2:50:22,  2.64s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 123/4000 [05:19<2:36:08,  2.42s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 124/4000 [05:21<2:36:28,  2.42s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 125/4000 [05:23<2:30:21,  2.33s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 126/4000 [05:26<2:33:04,  2.37s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 127/4000 [05:29<2:43:38,  2.54s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 128/4000 [05:32<2:57:32,  2.75s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 129/4000 [05:35<2:59:57,  2.79s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 130/4000 [05:37<2:45:50,  2.57s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 131/4000 [05:40<2:49:39,  2.63s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 132/4000 [05:42<2:42:29,  2.52s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 133/4000 [05:44<2:37:53,  2.45s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 134/4000 [05:47<2:37:00,  2.44s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 135/4000 [05:49<2:41:55,  2.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 136/4000 [05:52<2:52:02,  2.67s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 137/4000 [05:55<2:41:46,  2.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 138/4000 [05:57<2:31:23,  2.35s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 139/4000 [05:59<2:34:18,  2.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 140/4000 [06:01<2:32:14,  2.37s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 141/4000 [06:04<2:33:33,  2.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 142/4000 [06:06<2:34:06,  2.40s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 143/4000 [06:08<2:30:58,  2.35s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 144/4000 [06:12<2:48:28,  2.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 145/4000 [06:14<2:41:08,  2.51s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 146/4000 [06:16<2:32:47,  2.38s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 147/4000 [06:19<2:38:51,  2.47s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 148/4000 [06:21<2:33:31,  2.39s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▎         | 149/4000 [06:23<2:25:22,  2.27s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 150/4000 [06:26<2:40:01,  2.49s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 151/4000 [06:28<2:34:34,  2.41s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 152/4000 [06:31<2:45:44,  2.58s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 153/4000 [06:33<2:37:47,  2.46s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 154/4000 [06:36<2:44:02,  2.56s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 155/4000 [06:39<2:47:22,  2.61s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 156/4000 [06:41<2:47:42,  2.62s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 157/4000 [06:44<2:49:41,  2.65s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 158/4000 [06:47<2:58:41,  2.79s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 159/4000 [06:51<3:11:19,  2.99s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 160/4000 [06:53<2:56:09,  2.75s/it]Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [ ]:
print(predictions_finetuned[2])

CeritinIB and Thalidomamide have a Moderate interaction for Interaction involving antiplastic and immunoma diseases.

In [ ]:
%%time
from transformers import set_seed
set_seed(42)

index = 2010


# prompt = f"### Instruct: {inference_data[index]['question']} Can I take them together? Expain in 1-3 sentences.\n ### Output:\n"
prompt= inference_data[index]['prompt']

peft_model_res = gen(ft_model,prompt,250,)
peft_model_output = peft_model_res[0]
#print(peft_model_output)
prefix, success, result = peft_model_output.partition('#End')

dash_line = '-'.join('' for x in range(100))
print(dash_line)
print(f'INPUT PROMPT:\n{prompt}')
print(dash_line)
print(f'PEFT MODEL:\n{prefix}')
print(dash_line)
print(f'Ground Truth\n{inference_data[index]['Level'] + ' for ' + inference_data[index]['Category']}')

In [ ]:
=